version: "3"

services:
  nginx:
    image: 'nginx:latest'
    container_name: agent-pro-nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - .:/var/www/agent-pro/
    ports:
      - "7001:80"
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: agent-pro-app
    volumes:
      - .:/var/www/agent-pro/
    ports:
      - "5173:5173"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: agent-pro-mysql
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "7002:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    container_name: agent-pro-phpmyadmin
    restart: always
    ports:
      - 7003:80
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: 'redis:alpine'
    container_name: agent-pro-redis
    ports:
      - '7004:6379'
    volumes:
      - './docker/redis:/data'
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: agent-pro-mailpit
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'