version: "3"

services:
  nginx:
    image: 'nginx:latest'
    container_name: app_nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - .:/var/www/agent-pro/
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    build: 
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: app_php
    volumes:
      - .:/var/www/agent-pro/